run_id = "llama32-1b-pirate-sft-distro"
run_state = "WaitingForMembers"

[config]
warmup_time = 120
cooldown_time = 5
epoch_time = 480
max_round_train_time = 120
round_witness_time = 14
min_clients = 1
init_min_clients = 1

global_batch_size_start = 16
global_batch_size_end = 16
global_batch_size_warmup_tokens = 0

verification_percent = 0
witness_nodes = 1
total_steps = 200
waiting_for_members_extra_time = 120

[model.LLM]
architecture = "HfAuto"
data_type = "Finetuning"
max_seq_len = 1024
cold_start_warmup_steps = 0

[model.LLM.data_location]
Server = "train.aethercompute.org:39406"

[model.LLM.checkpoint.Hub]
repo_id = "meta-llama/Llama-3.2-1B-Instruct"

[model.LLM.lr_schedule.Cosine]
base_lr = 2.0e-5
warmup_steps = 20
warmup_init_lr = 0.0
total_steps = 200
final_lr = 2.0e-6

[model.LLM.optimizer.Distro]
clip_grad_norm = 1.0
weight_decay = 0.0
compression_decay = 1.0
compression_topk = 6
compression_chunk = 64
quantize_1bit = false
